[package]
name = "bench"
version = "0.1.0"
edition = "2021"

[dependencies]
rpq = { path = "../../rpq" }
tokio = "1.10.0"
pprof = { version = "0.13", features = ["flamegraph", "protobuf", "protobuf-codec"] }
coarsetime = "0.1.34"

[profile.release]
debug = true
